name: Build
permissions:
  contents: write
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zstd

      - name: Install Theos & Procursus Toolchain
        run: |
          echo "installing theos"
          export THEOS=$(mktemp -d theos.XXXXX)
          echo "THEOS=$THEOS" >> $GITHUB_ENV

          git clone --recursive https://github.com/theos/theos.git $THEOS --depth=1

          echo "downloading llvm toolchain"
          mkdir -p $THEOS/toolchain/linux/iphone
          curl -sSLf https://github.com/theos/toolchain/releases/latest/download/linux-x86_64.tar.zst | tar -I zstd -xvf - -C $THEOS/toolchain/linux/iphone --strip-components=1

          if [[ -x $THEOS/toolchain/linux/iphone/bin/clang ]]; then
            echo "Successfully installed the toolchain!"
          else
            echo "Something appears to have gone wrong -- the toolchain is not accessible."
            exit 7
          fi

          echo "installing sdk !!"
          $THEOS/bin/install-sdk iPhoneOS16.5

      - name: Build
        run: |
          git submodule update --init --recursive
          
          # Build 1: Standard IPA
          rm -rf .theos
          make package FINALPACKAGE=1 STRIP=0

          # Build 2: TrollStore TIPA (Clean object cache first)
          rm -rf .theos
          make package FINALPACKAGE=1 STRIP=0 TROLLSTORE=1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GeodeLauncher
          path: packages/*.*

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Declare Version Variables
        id: ref
        run: |
          echo "version=$(cat VERSION | xargs)" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: GeodeLauncher
          path: ${{ github.workspace }}/artifacts

      - name: Rename files
        run: |
          cd artifacts
          for f in *.ipa; do [ -f "$f" ] && mv "$f" "${f%.ipa}_${{ steps.ref.outputs.hash }}.ipa"; done
          for f in *.tipa; do [ -f "$f" ] && mv "$f" "${f%.tipa}_${{ steps.ref.outputs.hash }}.tipa"; done

      - name: Update Development Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Development Release'
          body: Geode iOS development release for commit ${{ github.sha }}.
          files: |
            ./artifacts/*.ipa
            ./artifacts/*.tipa
